#!/usr/bin/env bash
# Run the magnitude gain sweep, one worker per task.
#
# Same execution model as the round-1/round-2 scripts: per-task configs with
# per-task output CSVs, so workers never contend and `resume: true` makes a
# re-run resume rather than recompute.
#
# NOTE -- do not edit this file while it is running.  bash reads a script
# incrementally rather than all at once, so editing it mid-run shifts the byte
# offset the interpreter is reading from and it resumes in the middle of a
# different line.  That happened to the round-2 script and produced a spurious
# "UNITS[@]: unbound variable" at the very end, after the real work and the
# summarizer had already completed.  Copy the file elsewhere and run the copy
# if it has to change while a run is in flight.
#
# Usage:
#   scripts/run_..._gain_sweep.sh [PYTHON] [JOBS] [THREADS]

set -uo pipefail

PYTHON="${1:-python3}"
MAX_JOBS="${2:-8}"
THREADS="${3:-1}"

STEM="task_preservation_tanh_h512_modcog_revised8_12k_seqbest_np_gain_sweep_p50_80"
CONFIG_DIR="configs/np_gain_sweep"
LOG_DIR="results/${STEM}/logs"

TASKS=(
  ctxdlydm2intseq
  ctxdlydm1intseq
  dlydm1intseq
  dlydm2intseq
  multidlydmintseq
  dm1seqr
  dm2seql
  dmsintseq
)

export OMP_NUM_THREADS="${THREADS}"
export MKL_NUM_THREADS="${THREADS}"
export OPENBLAS_NUM_THREADS="${THREADS}"
export VECLIB_MAXIMUM_THREADS="${THREADS}"
export NUMEXPR_NUM_THREADS="${THREADS}"
export TORCH_NUM_THREADS="${THREADS}"

mkdir -p "${LOG_DIR}"

echo "generating per-task configs..."
"${PYTHON}" scripts/generate_tanh_h512_modcog_revised8_np_gain_sweep_suite.py --validate-inputs || exit 1

echo
echo "launching up to ${MAX_JOBS} workers x ${THREADS} threads over ${#TASKS[@]} tasks"
declare -a PIDS=()
declare -a PIDTASK=()

for task in "${TASKS[@]}"; do
  while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do sleep 5; done
  cfg="${CONFIG_DIR}/${STEM}_${task}.json"
  log="${LOG_DIR}/${task}.log"
  echo "  start ${task}  (log: ${log})"
  "${PYTHON}" -u -m pruning_benchmark --mode suite --config "${cfg}" > "${log}" 2>&1 &
  PIDS+=("$!")
  PIDTASK+=("${task}")
done

status=0
for i in "${!PIDS[@]}"; do
  if wait "${PIDS[$i]}"; then
    echo "  done  ${PIDTASK[$i]}"
  else
    echo "  FAILED ${PIDTASK[$i]} -- see ${LOG_DIR}/${PIDTASK[$i]}.log" >&2
    status=1
  fi
done

echo
if (( status == 0 )); then
  echo "all tasks complete; summarizing"
  "${PYTHON}" scripts/summarize_tanh_h512_modcog_revised8_np_gain_sweep.py
else
  echo "one or more tasks failed; rerun this script to resume" >&2
fi
exit "${status}"
