#!/usr/bin/env bash
# Train the Mod-Cog eight at a given hidden size, one worker per network.
#
# 24 units = 8 tasks x 3 seeds. Each unit carries one network through BOTH
# phases (6,000 steps at lr 1.2e-3, then 6,000 more at lr 6e-4) in a single
# config, so units are independently parallel and independently resumable --
# `resume: true` skips any run_id already present in that unit's CSV, so a
# re-run continues rather than retraining.
#
# JOBS=12 by default: measured on the 11-core (5P + 6E) development machine as
# the throughput optimum for this codebase; 16 workers was 44% SLOWER than 12
# on an equivalent suite, and 8 left cores idle. Re-measure on other hardware
# rather than assuming.
#
# NOTE -- do not edit this file while it is running. bash reads a script
# incrementally, so an edit shifts the byte offset the interpreter is reading
# from and it resumes mid-line. Copy it and run the copy instead.
#
# Usage:
#   scripts/run_modcog_revised8_size_training.sh [PYTHON] [HIDDEN] [JOBS] [THREADS]

set -uo pipefail

PYTHON="${1:-python3}"
HIDDEN="${2:-1024}"
MAX_JOBS="${3:-12}"
THREADS="${4:-1}"

STEM="train_tanh_h${HIDDEN}_modcog_revised8_to12k_seqbest_no_l2"
CONFIG_DIR="configs/${STEM}"
LOG_DIR="results/${STEM}/logs"

TASKS=(ctxdlydm2intseq ctxdlydm1intseq dlydm1intseq dlydm2intseq
       multidlydmintseq dm1seqr dm2seql dmsintseq)
SEEDS=(0 1 2)

export OMP_NUM_THREADS="${THREADS}" MKL_NUM_THREADS="${THREADS}"
export OPENBLAS_NUM_THREADS="${THREADS}" VECLIB_MAXIMUM_THREADS="${THREADS}"
export NUMEXPR_NUM_THREADS="${THREADS}" TORCH_NUM_THREADS="${THREADS}"

mkdir -p "${LOG_DIR}"
# Clear stale logs. Each worker truncates its own log on start, but a unit that
# never starts keeps the previous run's content -- so a failed run leaves
# "failed ..." lines that a later grep over LOG_DIR happily counts as current.
# That cost real diagnostic time once; do not remove this.
rm -f "${LOG_DIR}"/*.log

echo "generating configs for H=${HIDDEN}..."
"${PYTHON}" scripts/generate_modcog_revised8_size_training_suite.py --hidden-size "${HIDDEN}" || exit 1

UNITS=()
for s in "${SEEDS[@]}"; do for t in "${TASKS[@]}"; do UNITS+=("${t}_seed${s}"); done; done

echo
echo "launching up to ${MAX_JOBS} workers x ${THREADS} threads over ${#UNITS[@]} networks"
declare -a PIDS=() PIDTASK=()
for unit in "${UNITS[@]}"; do
  while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do sleep 10; done
  cfg="${CONFIG_DIR}/${STEM}_${unit}.json"
  log="${LOG_DIR}/${unit}.log"
  "${PYTHON}" -u -m pruning_benchmark --mode suite --config "${cfg}" > "${log}" 2>&1 &
  PIDS+=("$!"); PIDTASK+=("${unit}")
done

status=0
for i in "${!PIDS[@]}"; do
  if ! wait "${PIDS[$i]}"; then
    echo "  FAILED ${PIDTASK[$i]} -- see ${LOG_DIR}/${PIDTASK[$i]}.log" >&2
    status=1
  fi
done

echo
if (( status == 0 )); then
  echo "all ${#UNITS[@]} networks trained; summarizing"
  "${PYTHON}" scripts/summarize_modcog_revised8_size_training.py --hidden-size "${HIDDEN}"
else
  echo "one or more networks failed; rerun this script to resume" >&2
fi
exit "${status}"
