#!/usr/bin/env bash
# Round 3 of the revision: everything the narrative still needs.
#
#   1. synaptic scaling on the noise-prune mask        H=512   216 runs
#   2. constant-factor cap, completing 50-80%          H=512   264 runs
#   3. constant-factor cap, transfer test              H=1024  360 runs
#
# Run sequentially so the three never compete for the same cores.
#
# CRASH / SLEEP SAFETY. The harness appends each finished run to its unit CSV
# immediately and resumes by run_id, so an interrupted suite loses at most the
# runs that were in flight. Re-running this exact script resumes; it never
# repeats finished work. Nothing here depends on the process surviving.
#
# NOTE -- do not edit this file while it is running; bash reads scripts
# incrementally. Copy it and run the copy instead.
#
# Usage:  scripts/run_revision_round3_all.sh [PYTHON] [JOBS] [THREADS]

set -uo pipefail
PYTHON="${1:-python3}"
MAX_JOBS="${2:-12}"
THREADS="${3:-1}"

export OMP_NUM_THREADS="${THREADS}" MKL_NUM_THREADS="${THREADS}"
export OPENBLAS_NUM_THREADS="${THREADS}" VECLIB_MAXIMUM_THREADS="${THREADS}"
export NUMEXPR_NUM_THREADS="${THREADS}" TORCH_NUM_THREADS="${THREADS}"

TASKS=(ctxdlydm2intseq ctxdlydm1intseq dlydm1intseq dlydm2intseq
       multidlydmintseq dm1seqr dm2seql dmsintseq)
SPARSITIES=(p50 p60 p70 p80)

run_suite () {
  local stem="$1"; shift
  local cfgdir="configs/${stem}"
  local logdir="results/${stem}/logs"
  mkdir -p "${logdir}"
  echo
  echo "=== ${stem} ==="
  local units=()
  for p in "${SPARSITIES[@]}"; do for t in "${TASKS[@]}"; do
    [ -f "${cfgdir}/${stem}_${t}_${p}.json" ] && units+=("${t}_${p}")
  done; done
  echo "  ${#units[@]} units, up to ${MAX_JOBS} workers"
  local pids=() names=()
  for unit in "${units[@]}"; do
    while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do sleep 10; done
    "${PYTHON}" -u -m pruning_benchmark --mode suite \
      --config "${cfgdir}/${stem}_${unit}.json" > "${logdir}/${unit}.log" 2>&1 &
    pids+=("$!"); names+=("${unit}")
  done
  local bad=0
  for i in "${!pids[@]}"; do
    wait "${pids[$i]}" || { echo "  FAILED ${names[$i]} -- ${logdir}/${names[$i]}.log" >&2; bad=1; }
  done
  (( bad == 0 )) && echo "  complete" || echo "  finished with failures (re-run to resume)" >&2
  return 0
}

echo "generating configs..."
"${PYTHON}" scripts/generate_tanh_h512_modcog_revised8_synaptic_scaling_suite.py --shard-by-sparsity || exit 1
"${PYTHON}" scripts/generate_modcog_revised8_fixedcap_completion_suite.py --hidden-size 512 --shard-by-sparsity || exit 1
"${PYTHON}" scripts/generate_modcog_revised8_fixedcap_completion_suite.py --hidden-size 1024 --shard-by-sparsity || exit 1

run_suite "task_preservation_tanh_h512_modcog_revised8_12k_seqbest_synaptic_p50_80"
run_suite "task_preservation_tanh_h512_modcog_revised8_12k_seqbest_fixedcapfull_p50_80"
run_suite "task_preservation_tanh_h1024_modcog_revised8_12k_seqbest_fixedcapfull_p50_80"

echo
echo "round 3 complete"
