#!/usr/bin/env bash
# The size task-preservation suite at 10-40%, sharded by (task, sparsity).
#
# Companion to run_modcog_revised8_size_taskpres.sh, which covers 50-80%. Same
# seven methods, same seed counts, same defaults -- only the sparsity grid
# differs, so the two concatenate into one 10-80% dataset.
#
# JOBS defaults to 8 rather than the 12 the 50-80% launcher uses. At H=1024 the
# per-worker footprint is dominated by the S-NP observable matrix (25,000
# samples x 1024 units) and this machine has 11 cores / 18 GB; 12 workers put it
# close enough to the memory ceiling to be worth avoiding on a multi-hour run.
# Measured cost at 8 workers: ~25 s/run single-threaded on the ng_T=30 tasks.
#
# Runs under `caffeinate -i` so a closed lid does not idle-sleep the suite.
#
# NOTE -- do not edit this file while it is running; bash reads scripts
# incrementally. Copy it and run the copy instead.
#
# Usage:
#   scripts/run_modcog_revised8_size_taskpres_lowsparsity.sh [PYTHON] [HIDDEN] [JOBS] [THREADS]

set -uo pipefail

PYTHON="${1:-python3}"
HIDDEN="${2:-1024}"
MAX_JOBS="${3:-8}"
THREADS="${4:-1}"

STEM="task_preservation_tanh_h${HIDDEN}_modcog_revised8_12k_seqbest_revised_task_only_p10_40"
CONFIG_DIR="configs/${STEM}"
LOG_DIR="results/${STEM}/logs"

TASKS=(ctxdlydm2intseq ctxdlydm1intseq dlydm1intseq dlydm2intseq
       multidlydmintseq dm1seqr dm2seql dmsintseq)
SPARSITIES=(p10 p20 p30 p40)

export OMP_NUM_THREADS="${THREADS}" MKL_NUM_THREADS="${THREADS}"
export OPENBLAS_NUM_THREADS="${THREADS}" VECLIB_MAXIMUM_THREADS="${THREADS}"
export NUMEXPR_NUM_THREADS="${THREADS}" TORCH_NUM_THREADS="${THREADS}"

mkdir -p "${LOG_DIR}"
# Clear stale logs, so a later grep over LOG_DIR cannot count a previous run's
# "failed ..." lines as current. That cost real diagnostic time once.
rm -f "${LOG_DIR}"/*.log

echo "generating configs for H=${HIDDEN} (checkpoint presence is enforced)..."
"${PYTHON}" scripts/generate_modcog_revised8_size_taskpres_lowsparsity_suite.py \
  --hidden-size "${HIDDEN}" --shard-by-sparsity || exit 1

UNITS=()
for t in "${TASKS[@]}"; do for p in "${SPARSITIES[@]}"; do UNITS+=("${t}_${p}"); done; done

echo
echo "launching up to ${MAX_JOBS} workers x ${THREADS} threads over ${#UNITS[@]} units"
declare -a PIDS=() PIDTASK=()
for unit in "${UNITS[@]}"; do
  while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do sleep 10; done
  cfg="${CONFIG_DIR}/${STEM}_${unit}.json"
  log="${LOG_DIR}/${unit}.log"
  "${PYTHON}" -u -m pruning_benchmark --mode suite --config "${cfg}" > "${log}" 2>&1 &
  PIDS+=("$!"); PIDTASK+=("${unit}")
done

status=0
for i in "${!PIDS[@]}"; do
  if ! wait "${PIDS[$i]}"; then
    echo "  FAILED ${PIDTASK[$i]} -- see ${LOG_DIR}/${PIDTASK[$i]}.log" >&2
    status=1
  fi
done

echo
if (( status == 0 )); then
  echo "all ${#UNITS[@]} units complete"
else
  echo "one or more units failed; rerun this script to resume" >&2
fi
exit "${status}"
