#!/usr/bin/env bash
# Run the covariance-ablation suite at the official standard.
#
# Sharded by (task, sparsity) by default: 32 independent units rather than 8,
# so JOBS can exceed the number of tasks and fill cores the per-task layout
# leaves idle. Each unit has its own config and its own output CSV -- the suite
# harness rewrites the whole CSV on every append, so workers must never share
# one -- and `resume: true` makes a re-run resume rather than recompute.
#
# NOTE -- do not edit this file while it is running. bash reads a script
# incrementally, so editing it mid-run shifts the byte offset the interpreter
# reads from and it resumes mid-line. Copy it and run the copy instead.
#
# Usage:
#   scripts/run_..._covariance_ablation.sh [PYTHON] [JOBS] [THREADS] [SHARD]

set -uo pipefail

PYTHON="${1:-python3}"
MAX_JOBS="${2:-12}"
THREADS="${3:-1}"
SHARD="${4:-1}"

STEM="task_preservation_tanh_h512_modcog_revised8_12k_seqbest_noise_only_p50_80"
CONFIG_DIR="configs/noise_only"
LOG_DIR="results/${STEM}/logs"

TASKS=(ctxdlydm2intseq ctxdlydm1intseq dlydm1intseq dlydm2intseq
       multidlydmintseq dm1seqr dm2seql dmsintseq)
SPARSITIES=(p50 p60 p70 p80)

export OMP_NUM_THREADS="${THREADS}" MKL_NUM_THREADS="${THREADS}"
export OPENBLAS_NUM_THREADS="${THREADS}" VECLIB_MAXIMUM_THREADS="${THREADS}"
export NUMEXPR_NUM_THREADS="${THREADS}" TORCH_NUM_THREADS="${THREADS}"

mkdir -p "${LOG_DIR}"

GEN_ARGS=(--validate-inputs)
UNITS=("${TASKS[@]}")
if (( SHARD == 1 )); then
  GEN_ARGS+=(--shard-by-sparsity)
  UNITS=()
  for t in "${TASKS[@]}"; do for p in "${SPARSITIES[@]}"; do UNITS+=("${t}_${p}"); done; done
fi

echo "generating configs..."
"${PYTHON}" scripts/generate_tanh_h512_modcog_revised8_noise_only_suite.py "${GEN_ARGS[@]}" || exit 1

echo
echo "launching up to ${MAX_JOBS} workers x ${THREADS} threads over ${#UNITS[@]} units (SHARD=${SHARD})"
declare -a PIDS=() PIDTASK=()
for unit in "${UNITS[@]}"; do
  while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do sleep 5; done
  cfg="${CONFIG_DIR}/${STEM}_${unit}.json"
  log="${LOG_DIR}/${unit}.log"
  "${PYTHON}" -u -m pruning_benchmark --mode suite --config "${cfg}" > "${log}" 2>&1 &
  PIDS+=("$!"); PIDTASK+=("${unit}")
done

status=0
for i in "${!PIDS[@]}"; do
  if ! wait "${PIDS[$i]}"; then
    echo "  FAILED ${PIDTASK[$i]} -- see ${LOG_DIR}/${PIDTASK[$i]}.log" >&2
    status=1
  fi
done

echo
if (( status == 0 )); then
  echo "all units complete; summarizing"
  "${PYTHON}" scripts/summarize_tanh_h512_modcog_revised8_noise_only.py
else
  echo "one or more units failed; rerun this script to resume" >&2
fi
exit "${status}"
