#!/usr/bin/env bash
# H=1024 capped-rescale covariance ablation, sharded by (task, sparsity).
#
# Pairs the capped full-score arms against capped magnitude-only arms at four
# cap quantiles, to test whether capping restores the covariance contribution at
# the larger size the way it does at H=512. See the generator's docstring.
#
# NOTE -- do not edit this file while it is running; bash reads scripts
# incrementally. Copy it and run the copy instead.
#
# Usage:
#   scripts/run_modcog_revised8_size_capcov.sh [PYTHON] [HIDDEN] [JOBS] [THREADS]

set -uo pipefail

PYTHON="${1:-python3}"
HIDDEN="${2:-1024}"
MAX_JOBS="${3:-10}"
THREADS="${4:-1}"

STEM="task_preservation_tanh_h${HIDDEN}_modcog_revised8_12k_seqbest_capcov_p50_80"
CONFIG_DIR="configs/${STEM}"
LOG_DIR="results/${STEM}/logs"

TASKS=(ctxdlydm2intseq ctxdlydm1intseq dlydm1intseq dlydm2intseq
       multidlydmintseq dm1seqr dm2seql dmsintseq)
# Sparsity-major, and 60% first: capping moves retention at 50-60% at this size
# and does nothing measurable at 70-80%, so this order finishes the cells the
# suite exists to answer before it spends anything on the ones it does not.
SPARSITIES=(p60 p50 p70 p80)

export OMP_NUM_THREADS="${THREADS}" MKL_NUM_THREADS="${THREADS}"
export OPENBLAS_NUM_THREADS="${THREADS}" VECLIB_MAXIMUM_THREADS="${THREADS}"
export NUMEXPR_NUM_THREADS="${THREADS}" TORCH_NUM_THREADS="${THREADS}"

mkdir -p "${LOG_DIR}"
# Clear stale logs: a unit that never starts otherwise keeps the previous run's
# content, and a later grep over LOG_DIR counts its "failed" lines as current.
for f in "${LOG_DIR}"/*.log; do [ -e "$f" ] && mv "$f" "${f%.log}.prev.log"; done

echo "generating configs for H=${HIDDEN} (checkpoint presence is enforced)..."
"${PYTHON}" scripts/generate_modcog_revised8_size_capcov_suite.py \
  --hidden-size "${HIDDEN}" --shard-by-sparsity || exit 1

UNITS=()
for p in "${SPARSITIES[@]}"; do for t in "${TASKS[@]}"; do UNITS+=("${t}_${p}"); done; done

echo
echo "launching up to ${MAX_JOBS} workers x ${THREADS} threads over ${#UNITS[@]} units"
declare -a PIDS=() PIDTASK=()
for unit in "${UNITS[@]}"; do
  while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do sleep 10; done
  cfg="${CONFIG_DIR}/${STEM}_${unit}.json"
  log="${LOG_DIR}/${unit}.log"
  "${PYTHON}" -u -m pruning_benchmark --mode suite --config "${cfg}" > "${log}" 2>&1 &
  PIDS+=("$!"); PIDTASK+=("${unit}")
done

status=0
for i in "${!PIDS[@]}"; do
  if ! wait "${PIDS[$i]}"; then
    echo "  FAILED ${PIDTASK[$i]} -- see ${LOG_DIR}/${PIDTASK[$i]}.log" >&2
    status=1
  fi
done

echo
if (( status == 0 )); then
  echo "all ${#UNITS[@]} units complete"
else
  echo "one or more units failed; rerun this script to resume" >&2
fi
exit "${status}"
