#!/usr/bin/env bash
# Screen the covariance-estimator variants for S-NP at 50-70% sparsity.
#
# Sharded by (task, sparsity): 24 independent units, each with its own config
# and its own output CSV -- the suite harness rewrites the whole CSV on every
# append, so workers must never share one -- and `resume: true` makes a re-run
# resume rather than recompute.
#
# Stale logs are cleared first. A unit that never starts otherwise keeps the
# previous run's log, which has twice been read as a live failure.
#
# `caffeinate -i` holds the display awake for the duration.
#
# NOTE -- do not edit this file while it is running. bash reads a script
# incrementally, so editing it mid-run shifts the byte offset the interpreter
# reads from and it resumes mid-line. Copy it and run the copy instead.
#
# Usage:
#   scripts/run_tanh_h512_modcog_revised8_window_taskinput.sh [PYTHON] [JOBS] [THREADS]

set -uo pipefail

PYTHON="${1:-python3}"
MAX_JOBS="${2:-9}"
THREADS="${3:-1}"

STEM="task_preservation_tanh_h512_modcog_revised8_12k_seqbest_windowdrive_p50_70"
CONFIG_DIR="configs/window_drive"
LOG_DIR="results/${STEM}/logs"

TASKS=(ctxdlydm2intseq ctxdlydm1intseq dlydm1intseq dlydm2intseq
       multidlydmintseq dm1seqr dm2seql dmsintseq)
SPARSITIES=(p50 p60 p70)

export OMP_NUM_THREADS="${THREADS}" MKL_NUM_THREADS="${THREADS}"
export OPENBLAS_NUM_THREADS="${THREADS}" VECLIB_MAXIMUM_THREADS="${THREADS}"
export NUMEXPR_NUM_THREADS="${THREADS}" TORCH_NUM_THREADS="${THREADS}"

mkdir -p "${LOG_DIR}"
rm -f "${LOG_DIR}"/*.log

UNITS=()
for t in "${TASKS[@]}"; do for p in "${SPARSITIES[@]}"; do UNITS+=("${t}_${p}"); done; done

echo "generating configs..."
"${PYTHON}" scripts/generate_tanh_h512_modcog_revised8_window_taskinput_suite.py \
    --validate-inputs --shard-by-sparsity || exit 1

echo
echo "launching up to ${MAX_JOBS} workers x ${THREADS} threads over ${#UNITS[@]} units"
declare -a PIDS=() PIDTASK=()
for unit in "${UNITS[@]}"; do
  while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do sleep 5; done
  cfg="${CONFIG_DIR}/${STEM}_${unit}.json"
  log="${LOG_DIR}/${unit}.log"
  "${PYTHON}" -u -m pruning_benchmark --mode suite --config "${cfg}" > "${log}" 2>&1 &
  PIDS+=("$!"); PIDTASK+=("${unit}")
done

status=0
for i in "${!PIDS[@]}"; do
  if ! wait "${PIDS[$i]}"; then
    echo "  FAILED ${PIDTASK[$i]} -- see ${LOG_DIR}/${PIDTASK[$i]}.log" >&2
    status=1
  fi
done

echo
if (( status == 0 )); then
  echo "all units complete; summarizing"
  "${PYTHON}" scripts/summarize_tanh_h512_modcog_revised8_window_taskinput.py
else
  echo "one or more units failed; rerun this script to resume" >&2
fi
exit "${status}"
