#!/usr/bin/env bash
# Run the task-preservation suite at a given hidden size, sharded by (task, sparsity).
#
# Self-contained comparison *within* one size: every arm shares the same unpruned
# baseline, so the normalisation cancels and method contrasts are internally
# valid even where the unpruned accuracy differs from another size's.
#
# JOBS=12 is the measured optimum on the 11-core development machine (16 was 44%
# slower on an equivalent suite). At H=1024 the recurrent matmul is 4x larger and
# the machine is bandwidth-bound, so re-measure rather than assuming this carries.
#
# NOTE -- do not edit this file while it is running; bash reads scripts
# incrementally. Copy it and run the copy instead.
#
# Usage:
#   scripts/run_modcog_revised8_size_taskpres.sh [PYTHON] [HIDDEN] [JOBS] [THREADS]

set -uo pipefail

PYTHON="${1:-python3}"
HIDDEN="${2:-1024}"
MAX_JOBS="${3:-12}"
THREADS="${4:-1}"

STEM="task_preservation_tanh_h${HIDDEN}_modcog_revised8_12k_seqbest_capped_q50_q60_p50_80"
CONFIG_DIR="configs/${STEM}"
LOG_DIR="results/${STEM}/logs"

TASKS=(ctxdlydm2intseq ctxdlydm1intseq dlydm1intseq dlydm2intseq
       multidlydmintseq dm1seqr dm2seql dmsintseq)
SPARSITIES=(p50 p60 p70 p80)

export OMP_NUM_THREADS="${THREADS}" MKL_NUM_THREADS="${THREADS}"
export OPENBLAS_NUM_THREADS="${THREADS}" VECLIB_MAXIMUM_THREADS="${THREADS}"
export NUMEXPR_NUM_THREADS="${THREADS}" TORCH_NUM_THREADS="${THREADS}"

mkdir -p "${LOG_DIR}"
# Clear stale logs. Each worker truncates its own log on start, but a unit that
# never starts keeps the previous run's content -- so a failed run leaves
# "failed ..." lines that a later grep over LOG_DIR happily counts as current.
# That cost real diagnostic time once; do not remove this.
rm -f "${LOG_DIR}"/*.log

echo "generating configs for H=${HIDDEN} (checkpoint presence is enforced)..."
"${PYTHON}" scripts/generate_modcog_revised8_size_capped_suite.py \
  --hidden-size "${HIDDEN}" --shard-by-sparsity || exit 1

UNITS=()
for t in "${TASKS[@]}"; do for p in "${SPARSITIES[@]}"; do UNITS+=("${t}_${p}"); done; done

echo
echo "launching up to ${MAX_JOBS} workers x ${THREADS} threads over ${#UNITS[@]} units"
declare -a PIDS=() PIDTASK=()
for unit in "${UNITS[@]}"; do
  while (( $(jobs -rp | wc -l) >= MAX_JOBS )); do sleep 10; done
  cfg="${CONFIG_DIR}/${STEM}_${unit}.json"
  log="${LOG_DIR}/${unit}.log"
  "${PYTHON}" -u -m pruning_benchmark --mode suite --config "${cfg}" > "${log}" 2>&1 &
  PIDS+=("$!"); PIDTASK+=("${unit}")
done

status=0
for i in "${!PIDS[@]}"; do
  if ! wait "${PIDS[$i]}"; then
    echo "  FAILED ${PIDTASK[$i]} -- see ${LOG_DIR}/${PIDTASK[$i]}.log" >&2
    status=1
  fi
done

echo
if (( status == 0 )); then
  echo "all ${#UNITS[@]} units complete"
else
  echo "one or more units failed; rerun this script to resume" >&2
fi
exit "${status}"
